
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  tracker-lists: 192.168.1.114:22122



qiniu:
#  七牛云认证信息
  auth:
    accessKey: CKrKjbBqfhJYf8ZnhDAutb0THkzCCb62BPFg-39u
    secretKey: Rq6DGWqv6vLoDWM8nqv76BQ_ovEKJ3Y3VLYPl8PS
#  存储空间信息
  bucket:
    zone: zone1
    name: hzz-huancui
    downUrl: http://papay549o.bkt.clouddn.com


spring:
  datasource:
    name: fileserverDB
    url: jdbc:mysql://192.168.1.185:3306/cloud_file?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ming8858
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    druid:
#     监控后台账号和密码
      stat-view-servlet:
        login-username: admin
        login-password: charsming619

      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000